class TrackError(Exception): ...


class TrackNotFoundError(TrackError): ...


class RoleNotFoundError(TrackError): ...


class EventError(Exception): ...


class EventNotFoundError(EventError): ...


class ParticipantError(EventError): ...


class ParticipantNotFoundError(ParticipantError): ...


class PaginationError(EventError): ...


class TeamError(Exception): ...


class TeamNotFoundError(TeamError): ...


class TeamAlreadyExistsError(TeamError): ...


class TeamOperationError(TeamError): ...
