class TrackError(Exception): ...


class TrackNotFoundError(TrackError): ...


class RoleNotFoundError(TrackError): ...


class EventError(Exception): ...


class EventRepositoryError(EventError): ...


class EventNotFoundError(EventError): ...


class EventAlreadyExistsError(EventError): ...


class ParticipantError(EventError): ...


class ParticipantNotFoundError(ParticipantError): ...


class PaginationError(EventError): ...


class TeamError(Exception): ...


class TeamNotFoundError(TeamError): ...


class TeamAlreadyExistsError(TeamError): ...


class TeamOperationError(TeamError): ...


class ParticipantAlreadyInTeam(TeamError): ...


class InvitationError(Exception): ...


class InvitationNotFoundError(InvitationError): ...


class InvitationAlreadyExistsError(InvitationError): ...


class InvitationOperationError(InvitationError): ...


class JoinRequestError(Exception): ...


class JoinRequestNotFoundError(JoinRequestError): ...


class JoinRequestAlreadyExistsError(JoinRequestError): ...


class JoinRequestOperationError(JoinRequestError): ...
