from typing import Protocol
from src.models.track import Track
import uuid


class EventRepository(Protocol): ...


class TrackRepository(Protocol):
    def create_track(self, track: Track) -> uuid.UUID: ...
    def update_track(self, track: Track) -> None: ...
    def delete_track(self, id: uuid.UUID) -> None: ...
    def get_track(self, id: uuid.UUID) -> Track: ...
    def get_tracks_by_event_id(self, event_id: uuid.UUID) -> list[Track]: ...


class KafkaProducer(Protocol):
    def send_create_track(self, track: Track) -> None: ...
    def send_update_track(self, track: Track) -> None: ...
    def send_delete_track(self, id: uuid.UUID) -> None: ...
