from typing import Protocol
from src.models.track import Track
from src.models.event import Event, Participant
import uuid


class EventRepository(Protocol):
    async def get_event_by_id(self, event_id: uuid.UUID) -> Event: ...
    async def get_events_page_by_id(self, event_id: uuid.UUID, limit) -> list[Event]: ...
    async def get_events_page_by_num(self, offset: int, limit: int) -> list[Event]: ...
    async def create_event(self, event: Event) -> None: ...
    async def update_event(self, event: Event) -> None: ...
    async def delete_event(self, event_id: uuid.UUID) -> None: ...
    async def add_participant(
        self, event_id: uuid.UUID, participant: Participant
    ) -> None: ...
    async def get_participants_by_id(
        self, event_id: uuid.UUID, participant_id: uuid.UUID, limit: int
    ) -> list[Participant]: ...
    async def get_participants_by_num(
        self, event_id: uuid.UUID, offset: int, limit: int
    ) -> list[Participant]: ...


class TrackRepository(Protocol):
    async def create_track(self, track: Track): ...
    async def update_track(self, track: Track) -> None: ...
    async def delete_track(self, id: uuid.UUID) -> None: ...
    async def get_track(self, id: uuid.UUID) -> Track: ...
    async def get_tracks_by_event_id(self, event_id: uuid.UUID) -> list[Track]: ...


class KafkaProducer(Protocol):
    async def send_create_track(self, track: Track) -> None: ...
    async def send_update_track(self, track: Track) -> None: ...
    async def send_delete_track(self, id: uuid.UUID) -> None: ...

    async def send_create_event(self, event: Event) -> None: ...
    async def send_update_event(self, event: Event) -> None: ...
    async def send_delete_event(self, event_id: uuid.UUID) -> None: ...
    async def send_participant(
        self, event: Event, participant_id: uuid.UUID
    ) -> None: ...
