{
 "title": "Database",
 "description": "Dashboard of the database for all 3 modules",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_query_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Queries by Service",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    sum by (service) (db_query_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Queries RPS by Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (table, operation) (rate(db_query_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Query Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, table, operation) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Slowest Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum by (service, table, operation) (rate(db_query_duration_seconds_sum[5m])) / sum by (service, table, operation) (rate(db_query_duration_seconds_count[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Query Duration P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, table, operation) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}