{
 "title": "Event Module",
 "description": "Dashboards for event module of the service",
 "time": { "from": "2026-05-17T09:23:44.762Z", "to": "2026-05-17T13:50:28.799Z" },
 "panels": [
  {
   "title": "Event Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(business_operations_total{service=\"event_service\", status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Operations by Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (business_operations_total{service=\"event_service\", status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(business_operations_total{service=\"event_service\", status=\"error\"}[5m])) / sum(rate(business_operations_total{service=\"event_service\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Operations RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(business_operations_total{service=\"event_service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Operations Success vs Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum by (status) (rate(business_operations_total{service=\"event_service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Errors by Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (operation, error_type) (rate(business_operation_errors_total{service=\"event_service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}