{
 "title": "Kafka",
 "description": "Kafka service dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Total Sent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_messages_sent_total{status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_messages_sent_total{status=\"error\"}[5m])) / sum(rate(kafka_messages_sent_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Success vs Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kafka_messages_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_messages_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Errors by Topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (topic, service) (rate(kafka_messages_sent_total{status=\"error\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}