import uuid
from typing import Protocol

from src.models.invitation import Invitation, JoinRequest


class InvitationService(Protocol):
    async def create_invitation(self, invitation: Invitation) -> uuid.UUID: ...

    async def get_invitation(self, invitation_id: uuid.UUID) -> Invitation: ...

    async def get_invitations_by_team(
        self, team_id: uuid.UUID
    ) -> list[Invitation]: ...

    async def cancel_invitation(self, invitation_id: uuid.UUID) -> None: ...

    async def accept_invitation(self, invitation_id: uuid.UUID) -> None: ...

    async def reject_invitation(self, invitation_id: uuid.UUID) -> None: ...

    async def create_join_request(
        self, join_request: JoinRequest
    ) -> uuid.UUID: ...

    async def get_join_request(
        self, join_request_id: uuid.UUID
    ) -> JoinRequest: ...

    async def get_join_requests_for_member(
        self, track_id: uuid.UUID, member_id: uuid.UUID
    ) -> list[JoinRequest]: ...

    async def cancel_join_request(self, join_request_id: uuid.UUID) -> None: ...

    async def accept_join_request(self, join_request_id: uuid.UUID) -> None: ...

    async def reject_join_request(self, join_request_id: uuid.UUID) -> None: ...
