import uuid

import psycopg_pool

from src.models import Event
from src.models.event import Participant


class EventPostgresRepository:
    def __init__(self, pool: psycopg_pool.AsyncConnectionPool) -> None:
        self._pool = pool

    async def get_event_by_id(self, event_id: uuid.UUID) -> Event: ...
    async def get_events_page_by_id(
        self, event_id: uuid.UUID, limit
    ) -> list[Event]: ...
    async def get_events_page_by_num(self, offset: int, limit: int) -> list[Event]: ...
    async def create_event(self, event: Event) -> None: ...
    async def update_event(self, event: Event) -> None: ...
    async def delete_event(self, event_id: uuid.UUID) -> None: ...
    async def add_participant(
        self, event_id: uuid.UUID, participant: Participant
    ) -> None: ...
    async def get_participants_by_id(
        self, event_id: uuid.UUID, participant_id: uuid.UUID, limit: int
    ) -> list[Participant]: ...
    async def get_participants_by_num(
        self, event_id: uuid.UUID, offset: int, limit: int
    ) -> list[Participant]: ...
