import uuid
from typing import Protocol
from src.models.team import Team, TeamStatusEnum


class TeamService(Protocol):
    async def get_team(self, team_id: uuid.UUID) -> Team: ...

    async def create_team(self, team: Team) -> uuid.UUID: ...

    async def update_team(self, team: Team) -> None: ...

    async def delete_team(self, team_id: uuid.UUID) -> None: ...

    async def leave_team(self, team_id: uuid.UUID, member_id: uuid.UUID) -> None: ...

    async def kick_member(self, team_id: uuid.UUID, member_id: uuid.UUID) -> None: ...

    async def team_submit(self, team_id: uuid.UUID) -> None: ...

    async def change_team_status(
        self, team_id: uuid.UUID, status: TeamStatusEnum
    ) -> None: ...

    async def change_member_role(
        self,
        team_id: uuid.UUID,
        member_id: uuid.UUID,
        new_role_id: uuid.UUID,
    ) -> None: ...

    async def get_teams_by_event_id(self, event_id: uuid.UUID) -> list[Team]: ...

    async def get_teams_by_user(self, user_id: uuid.UUID) -> list[Team]: ...

    async def get_user_team_in_event(
        self, user_id: uuid.UUID, event_id: uuid.UUID
    ) -> Team | None: ...
