import uuid
from typing import Protocol
from src.models.team import Team, TeamStatusEnum


class TeamService(Protocol):
    async def get_teams(self, team_id: uuid.UUID) -> Team: ...

    async def create_team(self, team: Team) -> uuid.UUID: ...

    async def update_team(self, team: Team) -> None: ...

    async def delete_team(self, team_id: uuid.UUID) -> None: ...

    async def leave_team(self, team_id: uuid.UUID, member_id: uuid.UUID) -> None: ...

    async def kick_member(self, team_id: uuid.UUID, member_id: uuid.UUID) -> None: ...

    async def team_submit(self, team_id: uuid.UUID) -> None: ...

    async def change_team_status(
        self, team_id: uuid.UUID, status: TeamStatusEnum
    ) -> None: ...
