from typing import Optional, Protocol
from src.models.event import Event, Participant, ParticipantEvent
import uuid


class EventRepository(Protocol):
    async def get_event_by_id(self, event_id: uuid.UUID) -> Event: ...
    async def get_events_page_by_id(
        self, event_id: uuid.UUID, limit: int
    ) -> tuple[list[Event], Optional[uuid.UUID]]: ...
    async def get_events_page_by_num(
        self, offset: int, limit: int
    ) -> tuple[list[Event], Optional[uuid.UUID]]: ...
    async def create_event(self, event: Event) -> None: ...
    async def update_event(self, event: Event) -> None: ...
    async def delete_event(self, event_id: uuid.UUID) -> None: ...
    async def add_participant(
        self, event_id: uuid.UUID, participant: Participant
    ) -> None: ...
    async def get_participants_by_id(
        self, event_id: uuid.UUID, participant_id: uuid.UUID, limit: int
    ) -> tuple[list[Participant], Optional[uuid.UUID]]: ...
    async def get_participants_by_num(
        self, event_id: uuid.UUID, offset: int, limit: int
    ) -> tuple[list[Participant], Optional[uuid.UUID]]: ...
    async def get_participant_events_by_num(
        self, participant_id: uuid.UUID, offset: int, limit: int
    ) -> tuple[list[ParticipantEvent], Optional[uuid.UUID]]: ...
    async def get_participant_events_by_id(
        self, participant_id: uuid.UUID, event_id: uuid.UUID, limit: int
    ) -> tuple[list[ParticipantEvent], Optional[uuid.UUID]]: ...


class KafkaProducer(Protocol):
    async def send_create_event(self, event: Event) -> None: ...
    async def send_update_event(self, event: Event) -> None: ...
    async def send_delete_event(self, event_id: uuid.UUID) -> None: ...
    async def send_participant(
        self, event: Event, participant_id: uuid.UUID
    ) -> None: ...
