from typing import Protocol
from src.models.event import Event, Participant
import uuid


class EventRepository(Protocol):
    async def get_event_by_id(self, event_id: uuid.UUID) -> Event | None: ...
    async def get_events_page_by_id(
        self, event_id: uuid.UUID, limit
    ) -> list[Event]: ...
    async def get_events_page_by_num(self, offset: int, limit: int) -> list[Event]: ...
    async def create_event(self, event: Event) -> None: ...
    async def update_event(self, event: Event) -> None: ...
    async def delete_event(self, event_id: uuid.UUID) -> None: ...
    async def add_participant(
        self, event_id: uuid.UUID, participant: Participant
    ) -> None: ...
    async def get_participants_by_id(
        self, event_id: uuid.UUID, participant_id: uuid.UUID, limit: int
    ) -> list[Participant]: ...
    async def get_participants_by_num(
        self, event_id: uuid.UUID, offset: int, limit: int
    ) -> list[Participant]: ...


class KafkaProducer(Protocol):
    async def send_create_event(self, event: Event) -> None: ...
    async def send_update_event(self, event: Event) -> None: ...
    async def send_delete_event(self, event_id: uuid.UUID) -> None: ...
    async def send_participant(
        self, event: Event, participant_id: uuid.UUID
    ) -> None: ...
