from typing import Protocol
from src.models.track import Track
import uuid


class TrackRepository(Protocol):
    async def create_track(self, track: Track) -> None: ...
    async def update_track(self, track: Track) -> None: ...
    async def delete_track(self, id: uuid.UUID) -> None: ...
    async def get_track(self, id: uuid.UUID) -> Track: ...
    async def get_tracks_by_event_id(self, event_id: uuid.UUID) -> list[Track]: ...


class KafkaProducer(Protocol):
    async def send_create_track(self, track: Track) -> None: ...
    async def send_update_track(self, track: Track) -> None: ...
    async def send_delete_track(self, track: Track) -> None: ...
