from typing import Protocol
import uuid
from src.models.team import Team, TeamStatusEnum
from src.models.event import Participant


class TeamRepository(Protocol):
    """Repository for team data access"""

    async def get_team(self, team_id: uuid.UUID) -> Team: ...

    async def remove_member(self, team: Team, user: Participant) -> None: ...

    async def delete_team(self, team_id: uuid.UUID) -> None: ...

    async def create_team(self, team: Team) -> None: ...

    async def update_team(self, team: Team) -> None: ...

    async def change_team_status(self, team: Team, status: TeamStatusEnum) -> None: ...


class KafkaProducer(Protocol):
    """Kafka producer for team events"""

    async def send_team_created(self, team: Team) -> None: ...

    async def send_team_updated(self, team: Team) -> None: ...

    async def send_team_deleted(self, team: Team) -> None: ...

    async def send_team_submitted(self, team: Team) -> None: ...

    async def send_member_left(self, team: Team, member: Participant) -> None: ...

    async def send_member_kicked(self, team: Team, member: Participant) -> None: ...
