class RepositoryError(Exception): ...


class TrackNotFoundError(Exception): ...


class EventNotFoundError(Exception): ...


class EventAlreadyExistsError(Exception): ...


class PaginationError(Exception): ...


class ParticipantNotFoundError(Exception): ...


class ParticipantAlreadyExistsError(Exception): ...


class TeamNotFoundError(Exception): ...


class TeamAlreadyExistsError(Exception): ...


class RoleNotFoundError(Exception): ...


class InvitationNotFoundError(Exception): ...


class InvitationAlreadyExistsError(Exception): ...


class JoinRequestNotFoundError(Exception): ...


class JoinRequestAlreadyExistsError(Exception): ...


class ParticipantAlreadyInTeamError(Exception): ...
