class TrackNotFoundError(Exception): ...


class RoleNotFoundError(Exception): ...


class EventNotFoundError(Exception): ...


class PaginationError(Exception): ...


class ParticipantNotFoundError(Exception): ...