class TrackNotFoundError(Exception): ...


class EventNotFoundError(Exception): ...


class PaginationError(Exception): ...


class ParticipantNotFoundError(Exception): ...


class TeamNotFoundError(Exception): ...


class UserNotFoundError(Exception): ...


class TeamAlreadyExistsError(Exception): ...
