import uuid
from typing import Protocol
from src.models.track import Track as TrackModel


class TrackService(Protocol):
    async def create_track(self, track: TrackModel) -> uuid.UUID: ...

    async def get_track(self, track_id: uuid.UUID) -> TrackModel: ...

    async def get_tracks_by_event_id(self, event_id: uuid.UUID) -> list[TrackModel]: ...

    async def update_track(self, track: TrackModel) -> None: ...

    async def delete_track(self, track_id: uuid.UUID) -> None: ...
