import uuid
from typing import Protocol, Optional

import fastapi

from src.models.event import Event as EventModel, Participant as ParticipantModel


class EventService(Protocol):
    async def create_event(self, event: EventModel) -> uuid.UUID: ...

    async def update_event(self, event: EventModel) -> None: ...

    async def delete_event(self, event_id: uuid.UUID) -> None: ...

    async def get_event_by_id(self, event_id: uuid.UUID) -> EventModel: ...

    async def get_participants(self, event_id: uuid.UUID) -> list[ParticipantModel]: ...

    async def create_participant(self, participant: ParticipantModel) -> uuid.UUID: ...

    async def get_events(self, event_id: Optional[uuid.UUID] = None, offset: Optional[int] = None, limit: int = 10) -> list[EventModel]: ...
